apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vb0yj6qay-python
  janus-idp.io/tekton: vb0yj6qay-python
  backstage.io/kubernetes-id: vb0yj6qay-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vb0yj6qay-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
